/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicaciónmp3;

import java.awt.Color;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kelvin Cano
 */
public class EditarDatos extends javax.swing.JFrame {

    /**
     * Creates new form jp
     */
    private ArrayList<IndiceNombre> indiceRegistros;
    private String puntero;
    private ArrayList<MP3> listaEditar;
    public EditarDatos(String cancion) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listaEditar = new ArrayList<MP3>();
        puntero = cancion;
    }

    public ArrayList<MP3> getListaEditar() {
        return listaEditar;
    }
    
    public void getData() throws FileNotFoundException, IOException {       
        RandomAccessFile lectura = new RandomAccessFile("canciones.data", "rw");
        short punteroIndice = lectura.readShort();
        lectura.seek(punteroIndice);
        for (int i = 0; i < lectura.length(); i++) {//Recorre el archivo para obtener los indices
            short posicionDatos = lectura.readShort();
            
            byte longitud = lectura.readByte();
            byte[] caracteres = new byte[longitud * 2];
            lectura.read(caracteres);
            String cancion = new String(caracteres);
            punteroIndice = (short)lectura.getFilePointer();
            
            lectura.seek(posicionDatos);                        
            byte longitud2 = lectura.readByte();
            byte[] caracteres2 = new byte[longitud2 * 2];
            lectura.read(caracteres2);
            String artista = new String(caracteres2);  
            
            byte longitud3 = lectura.readByte();
            byte[] caracteres3 = new byte[longitud3 * 2];
            lectura.read(caracteres3);
            String album = new String(caracteres3);  
            
            byte longitud4 = lectura.readByte();
            byte[] caracteres4 = new byte[longitud4 * 2];
            lectura.read(caracteres4);
            String fecha = new String(caracteres4); 
            
            byte longitud5 = lectura.readByte();
            byte[] caracteres5 = new byte[longitud5 * 2];
            lectura.read(caracteres5);
            String genero = new String(caracteres5); 
            
            byte longitud6 = lectura.readByte();
            byte[] caracteres6 = new byte[longitud6 * 2];
            lectura.read(caracteres6);
            String duracion = new String(caracteres6); 
            
            byte longitud7 = lectura.readByte();
            byte[] caracteres7 = new byte[longitud7 * 2];
            lectura.read(caracteres7);
            String URL = new String(caracteres7); 
            
            byte longitud8 = lectura.readByte();
            byte[] caracteres8 = new byte[longitud8 * 2];
            lectura.read(caracteres8);
            String direccionCancion = new String(caracteres8);
            
            byte longitud9 = lectura.readByte();
            byte[] caracteres9 = new byte[longitud9 * 2];
            lectura.read(caracteres9);
            String direccionLetra = new String(caracteres9);
            listaEditar.add(new MP3(artista, album, fecha, genero, duracion, URL, direccionCancion, direccionLetra));
            lectura.seek(punteroIndice);
            
            if (lectura.getFilePointer() == lectura.length() || cancion.equals(puntero) == true){
                                                      //Detiene el puntero si encuentra la canción                                                  
                break;
            }
        }
        lectura.close();
        //listaEditar.get(0).getNombre_artista();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombreCancion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreArtista = new javax.swing.JTextField();
        sFecha = new javax.swing.JTextField();
        sGenero = new javax.swing.JTextField();
        sURL = new javax.swing.JTextField();
        bCargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        direccionLetra = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconosalir.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 60, 60));

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Letra");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        getContentPane().add(nombreCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 350, -1));

        jLabel3.setBackground(new java.awt.Color(51, 102, 255));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Canción");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(51, 102, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Artista");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setBackground(new java.awt.Color(51, 102, 255));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setBackground(new java.awt.Color(51, 102, 255));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Genero");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setBackground(new java.awt.Color(51, 102, 255));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("URL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        getContentPane().add(nombreArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 350, -1));
        getContentPane().add(sFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 350, 30));
        getContentPane().add(sGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 350, -1));
        getContentPane().add(sURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 350, -1));

        bCargar.setText("Guardar Cambios");
        bCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCargarActionPerformed(evt);
            }
        });
        getContentPane().add(bCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 350, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dirección letra");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        getContentPane().add(direccionLetra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 350, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 204, 0));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre Canción", "Nombre Artista", "Fecha", "Genero", "URL", "Direccion Letra" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 150, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ab626f8b84973cc04d1bbcbac5c10478.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCargarActionPerformed
        try {
            this.MostrarDatosEnFrame();
        } catch (IOException ex) {
            Logger.getLogger(EditarDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCargarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        System.out.println(jComboBox1.getSelectedIndex());//Jala posicion que el usuario a seleccionado
        if(jComboBox1.getSelectedIndex() == 0){
            nombreCancion.setEnabled(true);
        }else if(jComboBox1.getSelectedIndex() == 1){
            nombreArtista.setEnabled(true);
        }else if(jComboBox1.getSelectedIndex() == 2){
            sFecha.setEnabled(true);
        }else if(jComboBox1.getSelectedIndex() == 3){
            sGenero.setEnabled(true);
        }else if(jComboBox1.getSelectedIndex() == 4){
            sURL.setEnabled(true);
        }else if(jComboBox1.getSelectedIndex() == 5){
            direccionLetra.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void MostrarDatosEnFrame() throws IOException{
        this.getData();
        nombreCancion.setEnabled(false);
        nombreArtista.setEnabled(false);
        sFecha.setEnabled(false);
        sGenero.setEnabled(false);
        sURL.setEnabled(false);
        jTextArea1.setEnabled(false);
        direccionLetra.setEnabled(false);
        nombreCancion.setText(this.puntero);
        nombreArtista.setText(listaEditar.get(listaEditar.size() - 1).getNombre_artista());
        sFecha.setText(listaEditar.get(listaEditar.size() - 1).getFecha_album());
        sGenero.setText(listaEditar.get(listaEditar.size() - 1).getGenero());
        sURL.setText(listaEditar.get(listaEditar.size() - 1).getURL());
        if(listaEditar.get(listaEditar.size() - 1).getDireccion_letra().equals("NI")){//Es porque hay direccion de letra
            System.out.println("=");
            FileReader reader = new FileReader(listaEditar.get(listaEditar.size() - 1).getDireccion_letra());
            jTextArea1.read(reader, listaEditar.get(listaEditar.size() - 1).getDireccion_letra());
        }else{
        }
        direccionLetra.setText(listaEditar.get(listaEditar.size() - 1).getDireccion_letra());
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCargar;
    private javax.swing.JTextField direccionLetra;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nombreArtista;
    private javax.swing.JTextField nombreCancion;
    private javax.swing.JTextField sFecha;
    private javax.swing.JTextField sGenero;
    private javax.swing.JTextField sURL;
    // End of variables declaration//GEN-END:variables
}
