/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicaciónmp3;

import java.awt.Color;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kelvin Cano
 */
public class EditarDatos extends javax.swing.JFrame {

    /**
     * Creates new form jp
     */
    private ArrayList<MP3> listaEditar;
    public EditarDatos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listaEditar = new ArrayList<MP3>();
    }
    
    public void getData() throws FileNotFoundException, IOException {       
        RandomAccessFile lectura = new RandomAccessFile("canciones.data", "rw");
        short punteroIndice = lectura.readShort();
        lectura.seek(punteroIndice);
        for (int i = 0; i < lectura.length(); i++) {//Recorre el archivo para obtener los indices
            short posicionDatos = lectura.readShort();
            
            byte longitud = lectura.readByte();
            byte[] caracteres = new byte[longitud * 2];
            lectura.read(caracteres);
            String cancion = new String(caracteres);   
            //nombreCancion.setText(cancion);
            lectura.seek(posicionDatos);                        
            
            byte longitud2 = lectura.readByte();
            byte[] caracteres2 = new byte[longitud2 * 2];
            lectura.read(caracteres2);
            String artista = new String(caracteres2);  
            
            byte longitud3 = lectura.readByte();
            byte[] caracteres3 = new byte[longitud3 * 2];
            lectura.read(caracteres3);
            String album = new String(caracteres3);  
            
            byte longitud4 = lectura.readByte();
            byte[] caracteres4 = new byte[longitud4 * 2];
            lectura.read(caracteres4);
            String fecha = new String(caracteres4); 
            
            byte longitud5 = lectura.readByte();
            byte[] caracteres5 = new byte[longitud5 * 2];
            lectura.read(caracteres5);
            String genero = new String(caracteres5); 
            
            byte longitud6 = lectura.readByte();
            byte[] caracteres6 = new byte[longitud6 * 2];
            lectura.read(caracteres6);
            //String duracion = new String(caracteres6); 
            
            byte longitud7 = lectura.readByte();
            byte[] caracteres7 = new byte[longitud7 * 2];
            lectura.read(caracteres7);
            String URL = new String(caracteres7); 
                        
            listaEditar.add(new MP3(artista, album, fecha, genero, "", URL, "", ""));
            lectura.seek(punteroIndice);                        
            if (lectura.getFilePointer() == lectura.length()) {//Rompe si llega al final del archivo
                break;
            }
        }
        System.out.println(" " +listaEditar.get(0).getNombre_artista());
        System.out.println(" " +listaEditar.size());
        //listaEditar.get(0).getNombre_artista();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombreCancion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreArtisa = new javax.swing.JTextField();
        sFecha = new javax.swing.JTextField();
        sGenero = new javax.swing.JTextField();
        sURL = new javax.swing.JTextField();
        bCargar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconosalir.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 60, 60));

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Letra");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        getContentPane().add(nombreCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 350, -1));

        jLabel3.setBackground(new java.awt.Color(51, 102, 255));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Canción");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(51, 102, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Artista");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setBackground(new java.awt.Color(51, 102, 255));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setBackground(new java.awt.Color(51, 102, 255));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Genero");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setBackground(new java.awt.Color(51, 102, 255));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("URL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        getContentPane().add(nombreArtisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 350, -1));
        getContentPane().add(sFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 350, 30));
        getContentPane().add(sGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 350, -1));
        getContentPane().add(sURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 350, -1));

        bCargar.setText("Cargar");
        bCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCargarActionPerformed(evt);
            }
        });
        getContentPane().add(bCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ab626f8b84973cc04d1bbcbac5c10478.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCargarActionPerformed
        try {
            getData();
            String a = listaEditar.get(0).getNombre_artista();
            nombreArtisa.setText(a);
        } catch (IOException ex) {
            Logger.getLogger(EditarDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCargar;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombreArtisa;
    private javax.swing.JTextField nombreCancion;
    private javax.swing.JTextField sFecha;
    private javax.swing.JTextField sGenero;
    private javax.swing.JTextField sURL;
    // End of variables declaration//GEN-END:variables
}
